name: ModDamage
main: com.ModDamage.ModDamage
version: 0.10 DEV
authors: [KoryuObihiro, ricochet1k, Spudstabber]
description: |
    Completely customize damage in Bukkit with ModDamage!
commands:
  moddamage:
    aliases: [md]
    description: "Basic ModDamage control"
softdepend: [Multiverse-Core, elRegions, WorldGuard, bPermissions, PermissionsBukkit, PermissionsEx, mcMMO]
